export const ValData = [
  {
    Val: 1,
    data: [
      {
        mode: 'fraud',
        division_goal: 1,
        m_division: 'Software',
        prodMat: 'AI Cores',
        prodMatSize: 1,
        employee_goal: 3,
        storage_goal: 8,
        speech_goal: 0,
        factory_goal: 0,
        dream_goal: 0,
        smart_goal: 7,
        stat_goal: 0,
        project_goal: 0,
        abc_goal: 0,
        adv_goal: 3,
        wilson_goal: 0,
        EmployeeRatio: 4.5
      },
      {
        mode: 'fraud',
        division_goal: 6,
        m_division: 'Real Estate',
        prodMat: 'Real Estate',
        prodMatSize: 20,
        employee_goal: 9,
        storage_goal: 18,
        speech_goal: 20,
        factory_goal: 0,
        dream_goal: 0,
        smart_goal: 30,
        stat_goal: 10,
        project_goal: 10,
        abc_goal: 20,
        adv_goal: 21,
        wilson_goal: 6,
        EmployeeRatio: 4.5
      },
      {
        mode: 'fraud',
        division_goal: 14,
        m_division: 'Real Estate',
        prodMat: 'Real Estate',
        prodMatSize: 20,
        employee_goal: 60,
        storage_goal: 135,
        speech_goal: 160,
        factory_goal: 0,
        dream_goal: 10,
        smart_goal: 150,
        stat_goal: 160,
        project_goal: 180,
        abc_goal: 120,
        adv_goal: 60,
        wilson_goal: 30,
        EmployeeRatio: 4.5
      },
      {
        mode: 'product',
        productMin: 20000,
        division_goal: 14,
        m_division: 'Tobacco',
        prodMat: 'Real Estate',
        prodMatSize: 20,
        employee_goal: 0,
        storage_goal: 50,
        speech_goal: 280,
        factory_goal: 280,
        dream_goal: 10,
        smart_goal: 150,
        stat_goal: 280,
        project_goal: 250,
        abc_goal: 200,
        adv_goal: 60,
        wilson_goal: 40,
        EmployeeRatio: 4.5
      },
    ],
  },
  {
    Val: 0.5,
    data: [
      {
        mode: 'fraud',
        division_goal: 1,
        m_division: 'Software',
        prodMat: 'AI Cores',
        prodMatSize: 1,
        employee_goal: 3,
        storage_goal: 8,
        speech_goal: 0,
        factory_goal: 0,
        dream_goal: 0,
        smart_goal: 7,
        stat_goal: 0,
        project_goal: 0,
        abc_goal: 0,
        adv_goal: 3,
        wilson_goal: 0,
        EmployeeRatio: 3
      },
      {
        mode: 'fraud',
        division_goal: 4,
        m_division: 'Real Estate',
        prodMat: 'Real Estate',
        prodMatSize: 20,
        employee_goal: 6,
        storage_goal: 12,
        speech_goal: 10,
        factory_goal: 0,
        dream_goal: 0,
        smart_goal: 10,
        stat_goal: 0,
        project_goal: 0,
        abc_goal: 10,
        adv_goal: 3,
        wilson_goal: 0,
        EmployeeRatio: 3
      },
      {
        mode: 'fraud',
        division_goal: 14,
        m_division: 'Real Estate',
        prodMat: 'Real Estate',
        prodMatSize: 20,
        employee_goal: 15,
        storage_goal: 75,
        speech_goal: 150,
        factory_goal: 0,
        dream_goal: 0,
        smart_goal: 80,
        stat_goal: 150,
        project_goal: 100,
        abc_goal: 150,
        adv_goal: 40,
        wilson_goal: 15,
        EmployeeRatio: 3
      },
      {
        mode: 'product',
        productMin: 20000,
        division_goal: 14,
        m_division: 'Tobacco',
        prodMat: 'Real Estate',
        prodMatSize: 20,
        employee_goal: 0,
        storage_goal: 50,
        speech_goal: 200,
        factory_goal: 150,
        dream_goal: 10,
        smart_goal: 100,
        stat_goal: 200,
        project_goal: 150,
        abc_goal: 150,
        adv_goal: 50,
        wilson_goal: 25,
        EmployeeRatio: 3
      },
    ],
  } 
];


export const BnValData = {
  "1": 1,
  "2": 1,
  "3": 1,
  "4": 1,
  "5": 0.5,
  "6": 0.2,
  "7": 0.2,
  "9": 0.5,
  "10": 0.5,
  "11": 0.1,
  "13": 0.001
}
